name: macOS ARM .app build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          set -euxo pipefail
          python -m pip install -U pip wheel setuptools
          pip install \
            pymupdf Pillow numpy opencv-python-headless zxing-cpp \
            tkinterdnd2-universal pyinstaller

      - name: Build .app with PyInstaller
        run: |
          set -euxo pipefail
          # tkinterdnd2 のデータ同梱（tkdnd2.9配下も確実に拾う）
          cat > hook-tkinterdnd2.py << 'PY'
          from PyInstaller.utils.hooks import collect_data_files
          datas = collect_data_files('tkinterdnd2', includes=['tkdnd2.9/*','TKDND*','*.txt','*.md'])
          PY
          pyinstaller -y app.spec
          ls -la dist

      # --- 署名 / 公証：Secrets が揃っている場合のみ実行 ---
      - name: Import signing certificate
        if: ${{ secrets.MAC_CERT_P12_BASE64 != '' && secrets.MAC_CERT_P12_PASSWORD != '' && secrets.MAC_CERT_IDENTITY != '' }}
        env:
          P12_BASE64: ${{ secrets.MAC_CERT_P12_BASE64 }}
          P12_PASSWORD: ${{ secrets.MAC_CERT_P12_PASSWORD }}
        run: |
          set -euxo pipefail
          echo "$P12_BASE64" | base64 --decode > signing.p12
          KEYCHAIN="$RUNNER_TEMP/build.keychain"
          security create-keychain -p "" "$KEYCHAIN"
          security default-keychain -s "$KEYCHAIN"
          security unlock-keychain -p "" "$KEYCHAIN"
          # 検索リストに明示追加（重要）
          security list-keychains -d user -s "$KEYCHAIN"
          # タイムアウト緩和
          security set-keychain-settings -lut 21600 "$KEYCHAIN"
          security import signing.p12 -k "$KEYCHAIN" -P "$P12_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" "$KEYCHAIN"
          rm -f signing.p12

      - name: Codesign .app (deep + hardened)
        if: ${{ secrets.MAC_CERT_P12_BASE64 != '' && secrets.MAC_CERT_P12_PASSWORD != '' && secrets.MAC_CERT_IDENTITY != '' }}
        env:
          CODE_SIGN_IDENTITY: ${{ secrets.MAC_CERT_IDENTITY }}
        run: |
          set -euxo pipefail
          APP="dist/PDF内QRコードに注釈追加.app"
          # ネストした dylib / so / 実行ファイルを先に署名
          find "$APP/Contents" -type f \( -name "*.dylib" -o -name "*.so" -o -perm -111 \) -print0 | \
            xargs -0 -I{} codesign --force --options runtime --timestamp --sign "$CODE_SIGN_IDENTITY" "{}" || true
          # バンドル本体
          codesign --deep --force --options runtime --timestamp --sign "$CODE_SIGN_IDENTITY" "$APP"
          codesign --verify --deep --strict --verbose=2 "$APP" || (codesign -dv --verbose=4 "$APP"; false)

      - name: Notarize .app (zip submit -> wait -> staple)
        if: ${{ secrets.APPLE_ID != '' && secrets.APPLE_TEAM_ID != '' && secrets.APPLE_APP_PASS != '' }}
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_APP_PASS: ${{ secrets.APPLE_APP_PASS }}
        run: |
          set -euxo pipefail
          APP="dist/PDF内QRコードに注釈追加.app"
          /usr/bin/zip -ry "App.zip" "$APP"
          xcrun notarytool submit "App.zip" \
            --apple-id "$APPLE_ID" \
            --team-id "$APPLE_TEAM_ID" \
            --password "$APPLE_APP_PASS" \
            --wait
          xcrun stapler staple "$APP"
          spctl -a -vvvv "$APP" || true
          codesign --verify --deep --strict --verbose=2 "$APP" || true

      - name: Upload .app bundle (signed or unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: qr-pdf-annotator-arm
          path: 'dist/PDF内QRコードに注釈追加.app'

      - name: Create .dmg from .app
        run: |
          set -euxo pipefail
          APP="dist/PDF内QRコードに注釈追加.app"
          DMG="PDF内QRコードに注釈追加.dmg"
          rm -f "$DMG"
          hdiutil create -volname "PDF内QRコードに注釈追加" -srcfolder "$APP" -ov -format UDZO "$DMG"
          # （任意）Secrets がある時だけ DMG も staple
          if [ -n "${{ secrets.APPLE_ID }}" ]; then
            xcrun stapler staple "$DMG" || true
          fi
          ls -la .

      - name: Upload .dmg
        uses: actions/upload-artifact@v4
        with:
          name: qr-pdf-annotator-dmg
          path: 'PDF内QRコードに注釈追加.dmg'
