name: macOS build (Intel & Apple Silicon)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-14   # Apple Silicon (arm64)
            arch: arm64
          - runner: macos-13   # Intel (x86_64)
            arch: x86_64
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show Python & arch
        run: |
          python -V
          python - << 'PY'
          import platform, sys
          print("machine:", platform.machine(), "processor:", platform.processor())
          print("sys.maxsize (bits):", 64 if sys.maxsize>2**32 else 32)
          PY

      - name: Install deps
        run: |
          python -m pip install -U pip wheel setuptools
          pip install -r requirements.txt

      - name: Build .app with PyInstaller
        run: |
          pyinstaller app.py \
            --name QRPdfAnnotator \
            --windowed --onedir --noconfirm \
            --hidden-import=tkinterdnd2 \
            --collect-all=tkinterdnd2 \
            --collect-submodules=tkinter \
            --collect-submodules=cv2 \
            --collect-submodules=fitz
          # ad-hoc codesign（任意）
          codesign --deep --force -s - "dist/QRPdfAnnotator.app" || true

      - name: Make DMG
        run: |
          hdiutil create -volname "QRPdfAnnotator" \
            -srcfolder "dist/QRPdfAnnotator.app" \
            -ov -format UDZO "QRPdfAnnotator-${{ matrix.arch }}.dmg"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: QRPdfAnnotator-${{ matrix.arch }}
          path: QRPdfAnnotator-${{ matrix.arch }}.dmg
